[project]
name = "final-code"
version = "0.1.0"
description = "Breaking Bad Chat Analyzer"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "matplotlib",
    "nltk",
    "joblib",
    "scikit-learn"
]
